language: node_js
node_js:
  - "10.14.1"

sudo: required

services:
  - docker
notifications:
  email: false
node_js:
  - node

before_install:
  - sudo apt-get install libsecret-1-dev
script:
  - echo 'npm ci:' && echo -en 'travis_fold:start:script.1\\r'
  - npm ci
  - echo -en 'travis_fold:end:script.1\\r'

  - docker-compose up -d graph-node
  - ./scripts/wait-for-it.sh 127.0.0.1:8545
  - ./scripts/wait-for-it.sh 127.0.0.1:8000
  - ./scripts/wait-for-it.sh 127.0.0.1:8020
  - echo -en 'travis_fold:end:script.2\\r'
  - npm run lint
  - npm run test
  - npm run build

after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release
